books_shop_example:
  outputs:
    dev:
      dbname:
      - dbname
      host:
      - host
      pass:
      - dev_password
      port:
      - port
      schema:
      - dev_schema
      threads:
      - 1 or more
      type: postgres
      user:
      - dev_username
    prod:
      dbname:
      - dbname
      host:
      - host
      pass:
      - prod_password
      port:
      - port
      schema:
      - prod_schema
      threads:
      - 1 or more
      type: postgres
      user:
      - prod_username
  target: dev
northwind_ex1:
  outputs:
    dev:
      dbname: ex1
      host: northwind
      pass: airflow
      port: 5454
      schema: out
      threads: 1
      type: postgres
      user: airflow
  target: dev
